---
layout: post
title: promise
---
```
let promise = new Promise(function(resolve, reject) {});
```
new Promise에 인자로 넣은 함수를 executor라고 하고, new Promise() 가 실행될 때 같이 실행된다. executor가 인자로 받는 resolve와 reject는 함수로, 우리가 executor를 만들때 호출해야 한다.

promise 객체는 state와 result라는 두개의 internal property가 있다. 그 값은 상황에 따라 다음과 같은 값들을 가진다.
* 이 promise에 연결된 resolve와 reject가 아직 호출되지 않은 경우  
```
{ [[state]]: "pending", [[result]]: undefined }
```
* resolve(value) 가 호출됐을 경우  
```
{ [[state]]: "fullfilled", [[result]]: value }
```
* reject(error) 가 호출됐을 경우
```
{ [[state]]: "rejected", [[result]]: error }
```

예를 들어,
```
let promise = new Promise(function(resolve, reject) {
    resolve(3);
});
console.log(promise);
```
만약 위 코드에서 console.log()가 internal property들도 출력해준다고 하면, console.log()가 실행될 때 resolve가 이미 호출된 상황이므로 위 코드의 실행 결과는 `{ [[state]]: "fullfilled", [[result]]: 3 }` 이다. 반면,
```
let promise = new Promise(function(resolve, reject) {
    setTimeout(() => resolve(3), 1000);
});
setInterval(() => console.log(promise), 10);
```
이 코드는 1초가 지날 때까지 `{ [[state]]: "pending", [[result]]: undefined }`를 출력하다가 그 이후부터는 `{ [[state]]: "fullfilled", [[result]]: 3 }`을 출력할 것이다.

promise 객체에는 then과 catch라는 메소드도 있다.
```
promise.then(function(result) {}, function(error) {});
```
위처럼 두 함수를 인자로 받는데, 첫번째가 resolve()가 호출됐을때 호출되는 함수로, resolve()를 호출할때 인자로 넣은 값이 인자로 들어오고, 두번째는 reject()가 호출됐을때 호출되는 함수로, 마찬가지로 reject()를 호출할때 인자로 넣은 값이 인자로 들어온다. 예를 들어,
```
let promise = new Promise(function(resolve, reject) {
    setTimeout(() => resolve(3), 1000);
});
promise.then(
    function(result) {
        console.log(result);
    },
    function(error) {
    }
);
```
```
let promise = new Promise(function(resolve, reject) {
    setTimeout(() => reject(3), 1000);
});
promise.then(
    function(result) {
    },
    function(error) {
        console.log(error);
    }
);
```
위 두 코드 모두 실행시 1초 후에 3이 출력된다. 위 두 예시처럼 executor에서 resolve()나 reject()중 하나만 호출되는 것이 분명하다면,
```
promise.then(function(result) {}, null);
```
이나
```
promise.then(null, function(error) {});
```
처럼 써도 되고, 두번째 예시는
```
promise.catch(function(error) {});
```
와 정확히 같다.
